.Dd May 21, 2017
.Dt BASE64.ENCODE 3
.Os

.Sh NAME
.Nm base64.encode
.Nd encode a byte slice to base64

.Sh SYNOPSIS
.Sy use base64
.Pp
.Ft void
.Fo base64.decode
.Fa "bufi : byte[:]" "bufo : byte[:]"
.Fc

.Sh DESCRIPTION
.Fn base64.encode
encodes
.Fa bufi
from raw bytes
.Fa bufo
into the base64 format.
.Fa bufo
needs to be big enough to hold the encoded contents of
.Fa bufi .

.Sh RETURN VALUES
.Fn base64.encode
does not have any return values.

.Sh EXAMPLES
.Bd -literal -offset indent
use std
use base64

const main={
	var a, b, c

	a="H0=67.3;\enΩb=4.89;\enΩm=31.5;\enτ=0.0925;\enAs=2.215e-9;\enns=0.9603;\en"
	std.put(a)

	b=std.slalloc(base64.elen(a))
	base64.encode(a, b)
	std.put("{}\en", b)

	c=std.slalloc(base64.dlen(b))
	match base64.decode(b, c)
	| `std.Err e: std.fatal(e)
	| `std.Ok d: std.put(c)
	;;
}
.Ed

.Sh SEE ALSO
.Xr base64 1 ,
.Xr base64.elen 3 ,
.Xr base64.dlen 3 ,
.Xr base64.decode 3 ,
.Xr uudecode 1p ,
.Xr uuencode 1p .

.Sh STANDARDS
.Fn base64.encode
does not conform to any standards.

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
