.Dd May 21, 2017
.Dt BASE64.DLEN 3
.Os

.Sh NAME
.Nm base64.dlen
.Nd return the length a base64 encoded byte slice would occupy when decoded

.Sh SYNOPSIS
.Sy use base64
.Pp
.Ft std.size
.Fo base64.dlen
.Fa "buf : byte[:]"
.Fc

.Sh DESCRIPTION
.Fn base64.dlen
returns the length
.Fa buf
would require if it was decoded from base64.

.Sh EXAMPLES
.Bd -literal -offset indent
use std
use base64

const main={
	var a, b, c

	a="H0=67.3;\enΩb=4.89;\enΩm=31.5;\enτ=0.0925;\enAs=2.215e-9;\enns=0.9603;\en"
	std.put(a)

	b=std.slalloc(base64.elen(a))
	base64.encode(a, b)
	std.put("{}\en", b)

	c=std.slalloc(base64.dlen(b))
	match base64.decode(b, c)
	| `std.Err e: std.fatal(e)
	| `std.Ok d: std.put(c)
	;;
}
.Ed

.Sh SEE ALSO
.Xr base64 1 ,
.Xr base64.elen 3 ,
.Xr base64.decode 3 ,
.Xr base64.encode 3 ,
.Xr uudecode 1p ,
.Xr uuencode 1p .

.Sh STANDARDS
.Fn base64.dlen
does not conform to any standards.
